adjective1 = input("Enter an adjective: ")
adjective2 = input("Enter an adjective: ")
birdtype = input("Enter a type of bird: ")
roominhouse = input("Enter a room in a house: ")
verb = input("Enter a verb (past tense): ")
verb2 = input("Enter a verb: ")
relativename = input("Enter a relative's name: ")
noun = input("Enter a noun: ")
liquid = input("Enter a liquid: ")
ing = input("Enter a verb ending in -ing: ")
bodypartplural = input("Enter a part of the body (plural): ")
noun2 = input("Enter a plural noun: ")
ing2 = input("Enter a verb ending in -ing: ")
noun3 = input("Enter a noun: ")

print("It was a " + adjective1 + ", cold November day.")
print("I woke up to the " + adjective2 + " smell of " + birdtype + " roasting in the " + roominhouse + " downstairs.")
print("I " + verb + " down the stairs to see if I could help " + verb2 + " the dinner.")
print("My mom said,\"See if " + relativename + " needs a fresh " + noun + "\".")
print("So I carried a tray of glasses full of " + liquid + " into the " + ing + " room.")
print("When I got there, I couldn't believe my " + bodypartplural + " !")
print("There were " + noun2 + " " + ing2 + " on the " + noun3 + " !")